### ISSUE TITLE
Why return a promise?

### ISSUE THREAD

**Issue by captbaritone** [v12/m3u-parser#30]
None of the work is async, why pull in bluebird at all? Did you anticipate that you might be able to do some work async in the future?

**Comment by v12** [comment]
@captbaritone this was done in order not to block event loop when parsing massive playlists.

I had a lot of plans for this library back in the days but never got to it due to other commitments and lack of time to work on the project where this library was used...

**Comment by captbaritone** [comment]
But there is nothing actually async within the parser, so it's still going to block the event loop, right? I guess it might defer the work until the _next_ event loop, but it would still block.

Not trying to criticize, just trying to make sure I understand. I'm working on my own parser for https://github.com/captbaritone/webamp and was looking at yours for inspiration.
